# Generated by Django 4.2.2 on 2023-06-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('document', models.FileField(upload_to='', verbose_name='Документ')),
                ('created_date', models.DateField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ доставки',
                'verbose_name_plural': 'Документы доставки',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('orders', models.IntegerField(verbose_name='Количество заказов')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
                ('driver_license', models.BooleanField(verbose_name='Водительские права')),
                ('qualification', models.BooleanField(verbose_name='Квалификация')),
                ('medical_sertificate', models.BooleanField(verbose_name='Медицинское свидетельство')),
                ('employeement', models.BooleanField(verbose_name='Трудоустройство')),
                ('recomment', models.IntegerField(verbose_name='Рекомендация')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ водителя',
                'verbose_name_plural': 'Документы водителя',
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/feedback/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение отзыва',
                'verbose_name_plural': 'Изображения отзывов',
            },
        ),
        migrations.CreateModel(
            name='MessageDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documet', models.FileField(upload_to='', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ сообщения',
                'verbose_name_plural': 'Документы сообщения',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
                ('type_user', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('COMPANY', 'Company')], max_length=255, verbose_name='Тип пользователя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('size', models.FloatField(verbose_name='Размер')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('start_place', models.CharField(max_length=255, verbose_name='Место отправления')),
                ('end_place', models.CharField(max_length=255, verbose_name='Место доставки')),
                ('type_order', models.CharField(max_length=255, verbose_name='Тип заказа')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('type_car', models.CharField(choices=[('BIG', 'Big'), ('SMALL', 'Small')], max_length=255, verbose_name='Тип автомобиля')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chat', verbose_name='Чат')),
                ('documets', models.ManyToManyField(to='app.messagedoc', verbose_name='Документы сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водитель')),
                ('image', models.ManyToManyField(to='app.feedbackimage', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='documents',
            field=models.ManyToManyField(to='app.driverdocument', verbose_name='Документы водителя'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('NICE', 'Nice'), ('BAD', 'Bad')], max_length=255, verbose_name='Статус')),
                ('documents', models.ManyToManyField(to='app.deliverydocs', verbose_name='Документы доставки')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='CompanyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Компания')),
                ('images', models.ManyToManyField(to='app.feedbackimage', verbose_name='Изображения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о компании',
                'verbose_name_plural': 'Отзывы о компаниях',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='drivers',
            field=models.ManyToManyField(to='app.driver', verbose_name='Водители'),
        ),
        migrations.AddField(
            model_name='chat',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь'),
        ),
    ]
